### ISSUE TITLE
Pairing problem

### ISSUE THREAD

**Issue by aboutandre** [turtl/chrome-bookmarker#1]
The desktop app is running but there is nowhere to place the pairing code. 

When I click on the extension (Chrome) it triggers a popup with a pairing code asking to pair it with the extension. But where should I paste this?

Mac 10.11.5 and newest Chrome

**Comment by orthecreedence** [comment]
Once you copy the code, try clicking the button again. It should pop up a text box in the browser.

Also, I just remembered, on OSx the Turtl pairing dialog can sometimes cover the pairing popup in the browser! Try closing the pairing dialog and there should be a text box to paste under it.

**Comment by aboutandre** [comment]
Yes it works.

But this is a really bad UX problem. In the Chrome store there are also other people that didn't manage to sync the extension... =\
